#/*
# * Revision Control Information
# *
# * $Source: /vol/opua/opua2/sis/sis-1.2/common/src/RCS/Makefile.nooct,v $
# * $Author: sis $
# * $Revision: 1.5 $
# * $Date: 1994/07/15 22:53:30 $
# *
# */
# run this with make -i
#
# To compile jedi on the RS6000, add -lbsd to the LDFLAGS variable
# in the Makefile.
#
# To compile xsis, the graphical front end to sis, MIT X11R4 or X11R5
# is needed.  xsis is based on the X Toolkit and Athena widget set.  If
# you don't have this, just comment out the xsis lines in this file.
# All sis commands will work without xsis except plot_blif.
#
MACHINE	= mips
SRCDIR	= /projects/sis/sis-1.2/common/src
X11	= /usr/sww/X11

SIS	= $(SRCDIR)/sis
CAD	= $(SRCDIR)/cad
BIN	= $(SRCDIR)/bin

CC	= cc

all:
	cd sis; make -f Makefile.nooct SIS=$(SIS) CAD=$(CAD) CC=$(CC); cd ..
	cd utility; make CAD=$(CAD) CC=$(CC) libutility.a; \
	mv libutility.a $(CAD)/lib; cd ..
	cd options; make CAD=$(CAD) CC=$(CC) liboptions.a; \
	mv liboptions.a $(CAD)/lib; cd ..
	cd jedi; make CAD=$(CAD) CC=$(CC); cd ..
	cd espresso; make CAD=$(CAD) CC=$(CC); cd ..
	cd nova; make CAD=$(CAD) SIS=$(SIS) CC=$(CC); cd ..
	cd sred; make SIS=$(SIS) CC=$(CC); cd ..
	cd stamina; make MACHINE=$(MACHINE) CC=$(CC) SIS=$(SIS); cd ..
	cd vst2blif; make MACHINE=$(MACHINE) CC=$(CC); cd ..
	cd blif2vst; make MACHINE=$(MACHINE) CC=$(CC); cd ..
	cd xsis; make SIS=$(SIS) MACHINE=$(MACHINE) X11=$(X11) CC=$(CC); cd ..
	-cp -p sis/sis $(BIN)
	-cp -p jedi/jedi $(BIN)
	-cp -p sred/sred $(BIN)
	-cp -p stamina/bin/stamina $(BIN)
	-cp -p nova/nova $(BIN)
	-cp -p espresso/espresso $(BIN)
	-cp -p vst2blif/vst2blif $(BIN)
	-cp -p blif2vst/blif2vst $(BIN)
	-cp -p xsis/xsis $(BIN)
	strip $(BIN)/*

clean:
	cd sis; make SIS=$(SIS) CAD=$(CAD) clean; cd ..
	cd utility; make clean; cd ..
	-rm $(CAD)/lib/libutility.a
	cd options; make clean; cd ..
	-rm $(CAD)/lib/liboptions.a
	cd jedi; make clean; cd ..
	cd stamina; make clean; cd ..
	cd sred; make clean; cd ..
	cd nova; make clean; cd ..
	cd espresso; make clean; cd ..
	cd vst2blif; make clean; cd ..
	cd blif2vst; make clean; cd ..
	cd xsis; make clean; cd ..

cleanall: clean
	-rm -rf $(BIN)/*
	cd stamina; make cleanall; cd ..
	cd sis; make strip_depend; rm -rf lib/*; cd ..
	-rm -rf make.out Makefile
