# name of this package
NAME = bdd_cmu
CURRENT = /projects/sis/sis-devel/common/src/sis/bdd_cmu

# source files
SRC = bdd.c bddapply.c bddassoc.c bddblk.c bddcache.c bddcmp.c bddcomp.c bdddump.c bddhash.c \
bddmisc.c bddprimes.c bddprint.c bddprprofile.c bddqnt.c bddreduce.c bddrelprod.c \
bddreorder.c bddsat.c bddsize.c bddsupport.c bddswap.c bddunique.c bddwarn.c mtbdd.c bddcproject.c
HDR = bddint.h bdduser.h 
MISC = testbdd.c Makefile bdd.3

# search path for source files, separated by ":"
VPATH = $(CURRENT)/bdd_cmu/bdd_cmu:$(CURRENT)/include

# include file for building object libaries
include $(CURRENT)/Make_lib.include
