#/*
# * Revision Control Information
# *
# * $Source: /vol/opua/opua2/sis/sis-1.1/common/src/sis/include/RCS/Makefile,v $
# * $Author: sis $
# * $Revision: 1.2 $
# * $Date: 1992/05/06 19:03:59 $
# *
# */
includes:
	ln -s ../array/array.h
	ln -s ../astg/astg.h
	ln -s ../atpg/atpg.h
	ln -s ../atpg/sat.h
	ln -s ../avl/avl.h
	ln -s ../bdd/bdd.h
	ln -s ../clock/clock.h
	ln -s ../command/command.h
	ln -s ../decomp/decomp.h
	ln -s ../delay/delay.h
	ln -s ../enc/enc.h
	ln -s ../error/error.h
	ln -s ../espresso/espresso.h
	ln -s ../extract/extract.h
	ln -s ../factor/factor.h
	ln -s ../gcd/gcd.h
	ln -s ../graph/graph.h
	ln -s ../graph/graph_static.h
	ln -s ../graphics/graphics.h
	ln -s ../io/io.h
	ln -s ../latch/latch.h
	ln -s ../map/library.h
	ln -s ../linsolv/spMatrix.h
	ln -s ../linsolv/spConfig.h
	ln -s ../list/list.h
	ln -s ../lsort/lsort.h
	ln -s ../lsort/luniq.h
	ln -s ../map/map.h
	ln -s ../maxflow/maxflow.h
	ln -s ../mincov/mincov.h
	ln -s ../minimize/minimize.h
	ln -s ../network/network.h
	ln -s ../node/node.h
	ln -s ../node/nodeindex.h
	ln -s ../ntbdd/ntbdd.h
	ln -s ../octio/octio.h
	ln -s ../order/order.h
	ln -s ../phase/phase.h
	ln -s ../pld/pld.h
	ln -s ../power/power.h
	ln -s ../resub/resub.h
	ln -s ../retime/retime.h
	ln -s ../seqbdd/seqbdd.h
	ln -s ../simplify/simplify.h
	ln -s ../main/sis.h
	ln -s ../sparse/sparse.h
	ln -s ../speed/speed.h
	ln -s ../st/st.h
	ln -s ../stg/stg.h
	ln -s ../util/util.h
	ln -s ../util/ansi.h
	ln -s ../var_set/var_set.h

